import NavigationBar from './components/NavigationBar'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'] , weight:['100','200','400'] })

export const metadata = {
  title: 'CMS BLOG APP',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavigationBar>
      <body className={poppins.className}>{children}</body>
      </NavigationBar>
    </html>
  )
}
